# SERVER
server:
  port: 8080

# MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smarty_se401?createDatabaseIfNotExist=true
    username: root
    password: Goat123

# HIBERNATE
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# FLYWAY
  flyway:
    enabled: true
    baseline-on-migrate: true

# MAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: devsale23@gmail.com
    password: vtaz dykb rrkh yjag
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true
            required: true

# JWT TOKEN
app:
  jwt:
    secret-key: 5zAq4kNp2fTg7yHd3mYsVx8lBv6cXjWn1bMe0rLf9tKi2oJu1hGy3bHv5nQp8tRi0cWq3zXr6kLm9oNp4sYv6hGy3bHv5nQ
    expiration: 1800000
