# SERVER
server:
  port: 8080

# MYSQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smarty_se401?createDatabaseIfNotExist=true
    username: root
    password: Goat123

# HIBERNATE
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# FLYWAY
  flyway:
    enabled: true
    baseline-on-migrate: true
